name: TSL_py3_10
channels:
  - pytorch
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/intel
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/intel/
  - nvidia
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/pro
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.6.2=hbcca054_0
  - certifi=2024.2.2=pyhd8ed1ab_0
  - cuda-cudart=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-runtime=11.8.0=0
  - cuda-version=13.1=hd92462c_3
  - dpcpp-cpp-rt=2024.2.0=intel_981
  - dpcpp_cpp_rt=2024.2.0=intel_981
  - expat=2.7.3=h3385a95_0
  - ffmpeg=4.2.2=h20bf706_0
  - fortran_rt=2024.2.0=intel_981
  - freetype=2.13.3=h4a9f257_0
  - giflib=5.2.2=h5eee18b_0
  - gmp=6.3.0=h6a678d5_0
  - gnutls=3.6.15=he1e5248_0
  - icc_rt=2024.2.0=intel_981
  - intel-cmplr-lib-rt=2024.2.0=intel_981
  - intel-cmplr-lib-ur=2024.2.0=intel_981
  - intel-cmplr-lic-rt=2024.2.0=intel_981
  - intel-fortran-rt=2024.2.0=intel_981
  - intel-opencl-rt=2024.2.0=intel_981
  - intel-openmp=2024.2.0=intel_981
  - intel-sycl-rt=2024.2.0=intel_981
  - intelpython=2024.2.0=0
  - joblib=1.4.2=pyhd8ed1ab_0
  - jpeg=9b=0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libcublas=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufile=1.16.0.49=h3b4bcfc_0
  - libcurand=10.4.1.34=h5dabb87_0
  - libcusolver=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgomp=15.2.0=h4751f2c_7
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libnpp=11.8.0.86=0
  - libnsl=2.0.0=h5eee18b_0
  - libnvjpeg=11.9.0.86=0
  - libopus=1.3.1=h5eee18b_1
  - libpng=1.6.50=h2ed474d_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libtasn1=4.20.0=ha30cf84_0
  - libtiff=4.1.0=h2733197_1
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libvpx=1.7.0=h439df22_0
  - libwebp=1.2.0=h89dd481_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_1
  - mkl=2024.0.0=intel_49656
  - mkl_fft=1.3.6=py310h1d81ff8_61
  - mkl_random=1.2.2=py310h5a378b4_81
  - mkl_umath=0.1.1=py310h2b1685c_91
  - mpc=1.0.3=0
  - mpfr=4.2.1=h5eee18b_0
  - ncurses=6.5=h7934f7d_0
  - nettle=3.7.3=hbbd107a_1
  - numpy-base=1.24.3=py310hbac2b65_5
  - openh264=2.1.1=h4ff587b_0
  - openssl=3.3.1=h4ab18f5_0
  - pip=25.3=pyhc872135_0
  - pooch=1.8.2=pyhd8ed1ab_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.10.19=h6fa692b_0
  - python_abi=3.10=2_cp310
  - pytorch=2.2.1=py3.10_cuda11.8_cudnn8.7.0_0
  - pytorch-cuda=11.8=h7e8668a_6
  - pytorch-mutex=1.0=cuda
  - readline=8.3=hc2a1206_0
  - sqlite=3.51.0=h2a70700_0
  - tbb=2021.13.0=intel_628
  - tbb4py=2021.13.0=py310_intel_628
  - tk=8.6.15=h54e0aa7_0
  - torchtriton=2.2.0=py310
  - typing_extensions=4.15.0=py310h06a4308_0
  - x264=1!157.20191217=h7b6447c_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.4.9=haebb681_0
  - pip:
    - absl-py==2.3.1
    - accelerate==0.34.2
    - aiohappyeyeballs==2.6.1
    - aiohttp==3.13.2
    - aiosignal==1.4.0
    - annotated-types==0.7.0
    - anyio==4.12.0
    - async-timeout==5.0.1
    - attrs==25.4.0
    - axial-positional-embedding==0.1.0
    - brotlicffi==1.2.0.0
    - cffi==2.0.0
    - charset-normalizer==3.4.4
    - chronos-forecasting==1.5.1
    - click==8.3.1
    - colt5-attention==0.11.1
    - contourpy==1.3.2
    - cycler==0.12.1
    - datasets==4.4.1
    - deprecated==1.3.1
    - dill==0.4.0
    - einops==0.8.1
    - einshape==1.0
    - exceptiongroup==1.3.1
    - filelock==3.20.0
    - fonttools==4.61.0
    - frozenlist==1.8.0
    - fsspec==2025.10.0
    - gitdb==4.0.12
    - gitpython==3.1.45
    - gmpy2==2.1.2
    - h11==0.16.0
    - hf-xet==1.2.0
    - httpcore==1.0.9
    - httpx==0.28.1
    - huggingface-hub==0.36.0
    - idna==3.11
    - inquirerpy==0.3.4
    - jinja2==3.1.6
    - kiwisolver==1.4.9
    - llvmlite==0.46.0
    - local-attention==1.9.14
    - markdown-it-py==4.0.0
    - markupsafe==3.0.2
    - matplotlib==3.10.7
    - mdurl==0.1.2
    - mkl-fft==1.3.6
    - mkl-random==1.2.2
    - mkl-service==2.4.0
    - mkl-umath==0.1.1
    - mpmath==1.3.0
    - multidict==6.7.0
    - multiprocess==0.70.18
    - narwhals==2.13.0
    - networkx==3.4.2
    - numba==0.63.0
    - numpy==1.26.4
    - packaging==25.0
    - pandas==1.5.3
    - patool==4.0.1
    - pfzy==0.3.4
    - pillow==9.3.0
    - platformdirs==4.5.1
    - product-key-memory==0.3.0
    - prompt-toolkit==3.0.52
    - propcache==0.4.1
    - protobuf==6.33.2
    - psutil==7.1.3
    - pyarrow==22.0.0
    - pycparser==2.23
    - pydantic==2.12.5
    - pydantic-core==2.41.5
    - pygments==2.19.2
    - pyparsing==3.2.5
    - pysocks==1.7.1
    - python-dateutil==2.9.0.post0
    - pytz==2025.2
    - pywavelets==1.8.0
    - pyyaml==6.0.3
    - reformer-pytorch==1.4.4
    - regex==2025.11.3
    - requests==2.32.5
    - rich==14.2.0
    - safetensors==0.7.0
    - scikit-base==0.8.3
    - scikit-learn==1.2.2
    - scipy==1.10.1
    - sentry-sdk==2.47.0
    - setuptools==80.9.0
    - shellingham==1.5.4
    - six==1.17.0
    - sktime==0.35.0
    - smmap==5.0.2
    - sympy==1.14.0
    - threadpoolctl==3.6.0
    - timesfm==1.3.0
    - tokenizers==0.22.1
    - torch==2.2.1
    - torchaudio==2.2.1
    - torchvision==0.17.1
    - tqdm==4.67.1
    - transformers==4.57.3
    - triton==2.2.0
    - typer==0.20.0
    - typing-extensions==4.15.0
    - typing-inspection==0.4.2
    - tzdata==2025.2
    - urllib3==2.5.0
    - utilsforecast==0.2.15
    - wandb==0.23.1
    - wcwidth==0.2.14
    - wheel==0.45.1
    - wrapt==2.0.1
    - xxhash==3.6.0
    - yarl==1.22.0
prefix: /home/Calvin/Softwares/anaconda3/envs/TSL_py3_10
